# These are supported funding platforms
github: { { PLACEHOLDER_GITHUB_USER } } # GitHub Sponsors
patreon: # Your Patreon username
ko_fi: # Your Ko-fi username
custom: ['www.wesolowski.dev'] # Up to 4 custom URLs
